const char* haikus[] = {
  "*Brume", "*matinale", "*sur", "*le", "*lac", "*silencieux.",
  "*Papillons", "*dansent", "*gracieusement", "*au", "*vent", "*d'ete.",
  "*Sous", "*les", "*cerisiers", "*les", "*petales", "*tombent", "*doucement.",
  "*Riviere", "*murmurante", "*parmi", "*les", "*pierres", "*anciennes.",
  "*Feuilles", "*d'automne", "*tourbillonnent", "*dans", "*le", "*vent", "*frais.",
  "*Soleil", "*couchant", "*embrase", "*l'horizon", "*dore.",
  "*Chants", "*d'oiseaux", "*reveillent", "*la", "*foret", "*endormie.",
  "*Lune", "*eclaire", "*doucement", "*la", "*clairiere", "*paisible.",
  "*Pluie", "*douce", "*caresse", "*les", "*fleurs", "*epanouies.",
  "*Etoiles", "*scintillent", "*dans", "*le", "*ciel", "*nocturne.",
  "*Rosee", "*du", "*matin", "*brille", "*sur", "*les", "*brins", "*d'herbe.",
  "*Ecureuil", "*frele", "*bondit", "*parmi", "*les", "*feuilles", "*mortes.",
  "*Montagne", "*lointaine", "*se", "*decoupe", "*dans", "*le", "*ciel", "*bleu.",
  "*Le", "*vent", "*chuchote", "*dans", "*les", "*pins", "*centenaires.",
  "*Mer", "*d'argent", "*sous", "*le", "*clair", "*de", "*lune", "*paisible.",
  "*Ruisseau", "*chantant", "*glisse", "*sur", "*les", "*cailloux", "*polis.",
  "*Ombres", "*dans", "*la", "*foret", "*dansent", "*avec", "*la", "*lumiere.",
  "*Hibou", "*solitaire", "*chante", "*a", "*la", "*nuit", "*naissante.",
  "*Nenuphars", "*flottent", "*calmes", "*sur", "*l'etang", "*miroitant.",
  "*Horizon", "*flou", "*au", "*crepuscule", "*s'eteint", "*doucement.",
  "*Le", "*givre", "*d'hiver", "*couvre", "*les", "*champs", "*endormis.",
  "*Odeurs", "*de", "*pins", "*dans", "*la", "*chaleur", "*de", "*l'ete.",
  "*Grillons", "*chantent", "*doucement", "*dans", "*la", "*nuit", "*chaude.",
  "*Rivage", "*calme", "*ou", "*les", "*vagues", "*se", "*brisent", "*doucement.",
  "*Arbre", "*ancien", "*ecoute", "*le", "*temps", "*qui", "*passe", "*lentement.",
  "*Papillon", "*blanc", "*vole", "*entre", "*les", "*fleurs", "*sauvages.",
  "*Brouillard", "*d'automne", "*cache", "*les", "*collines", "*lointaines.",
  "*Neige", "*eclatante", "*couvre", "*les", "*sommets", "*paisibles.",
  "*Lac", "*gele", "*reflete", "*la", "*pale", "*lumiere", "*du", "*jour.",
  "*Les", "*bruits", "*de", "*la", "*riviere", "*chantent", "*la", "*nature.",
  "*Chene", "*majestueux", "*s'etend", "*vers", "*le", "*ciel", "*bleu.",
  "*Cerf", "*dans", "*la", "*clairiere", "*observe", "*en", "*silence.",
  "*Rayons", "*du", "*soleil", "*traversent", "*la", "*foret", "*sombre.",
   "*Serveur", "*frugal", "*ronronne", "*avec", "*la", "*pluie.",
  "*Panneaux", "*solaires", "*tièdes", "*boivent", "*la", "*lumière.",
  "*Vent", "*dans", "*les", "*ailettes", "*refroidit", "*le", "*cœur.",
  "*Code", "*comme", "*lichens", "*s'accroche", "*au", "*rocher.",
  "*Graines", "*de", "*données", "*reposent", "*dans", "*la", "*terre.",
  "*Réseau", "*maillé", "*chuchote", "*entre", "*les", "*chênes.",
  "*Vieilles", "*cartes", "*mères", "*chauffent", "*les", "*fourmis.",
  "*Écran", "*e-ink", "*pâle", "*boit", "*l'aube", "*froide.",
  "*Courant", "*alternatif", "*imite", "*le", "*clapotis.",
  "*Algorithmes", "*lents", "*suivent", "*les", "*saisons.",
  "*CRON", "*de", "*la", "*rosée", "*réveille", "*les", "*nœuds.",
  "*Soudure", "*parfumée", "*résine", "*et", "*pin", "*murmurent.",
  "*Ventilateurs", "*éteints", "*respirent", "*la", "*nuit.",
  "*Serveurs", "*au", "*grenier", "*écoutent", "*les", "*pluies.",
  "*Cycles", "*du", "*compost", "*bouclent", "*nos", "*boucles.",
  "*Git", "*branche", "*et", "*branche", "*dans", "*le", "*verger.",
  "*Souris", "*sans", "*pile", "*court", "*sur", "*l'écorce.",
  "*Forêt", "*de", "*capteurs", "*veille", "*sans", "*parler.",
  "*Ondes", "*courtes", "*portent", "*le", "*chant", "*des", "*grues.",
  "*Batterie", "*au", "*sel", "*rêve", "*près", "*des", "*algues.",
  "*Turbines", "*et", "*bernaches", "*se", "*partagent", "*le", "*ciel.",
  "*Clavier", "*de", "*bois", "*claque", "*dans", "*la", "*cabane.",
  "*Programme", "*diurne", "*s'endort", "*au", "*coucher.",
  "*Lent", "*processeur", "*compte", "*les", "*étoiles.",
  "*Câbles", "*enterrés", "*caressés", "*par", "*les", "*taupes.",
  "*Soleil", "*d'hiver", "*compile", "*les", "*ombres.",
  "*Radio", "*amateur", "*salue", "*les", "*sommets.",
  "*Mémoire", "*flash", "*dort", "*dans", "*une", "*coquille.",
  "*Script", "*à", "*manivelle", "*relance", "*la", "*brise.",
  "*Recyclage", "*profond", "*fait", "*naître", "*des", "*oiseaux.",
  "*Nuit", "*hors", "*ligne", "*respire", "*avec", "*la", "*forêt.",
  "*Lune", "*réfléchie", "*sur", "*le", "*panneau.",
  "*Colibri", "*teste", "*le", "*débogueur", "*des", "*fleurs.",
  "*Brise", "*compile", "*lentement", "*les", "*pins.",
  "*Serveur", "*au", "*rameau", "*héberge", "*des", "*mousses.",
  "*Capsule", "*LoRa", "*réveille", "*le", "*pré.",
  "*Pluie", "*versionnée", "*merge", "*les", "*ruisseaux.",
  "*Tortue", "*routeur", "*porte", "*son", "*réseau.",
  "*Chamane", "*du", "*cloud", "*écoute", "*les", "*cailloux.",
  "*Gravier", "*et", "*bits", "*grincent", "*sous", "*le", "*pas.",
  "*Houblon", "*grimpe", "*le", "*mât", "*antenne.",
  "*Énergie", "*sobre", "*tisse", "*nos", "*outils.",
  "*Silence", "*cache", "*un", "*daemon", "*heureux.",
  "*Neige", "*sur", "*les", "*claviers", "*éteints.",
  "*Vieux", "*ThinkPad", "*tiède", "*à", "*la", "*bergerie.",
  "*Capteurs", "*ouverts", "*partagent", "*la", "*rosée.",
  "*Biosphère", "*et", "*BIOS", "*rient", "*ensemble.",
  "*Compost", "*de", "*codes", "*nourrit", "*demain.",
  "*Rivière", "*hors", "*cache", "*flux", "*permanent.",
  "*Graines", "*hashées", "*attendent", "*le", "*dégel.",
  "*Matin", "*sans", "*wifi", "*plus", "*clair.",
  "*Soleil", "*de", "*mai", "*recharge", "*les", "*abeilles.",
  "*Vent", "*pair", "*à", "*pair", "*dans", "*les", "*épis.",
  "*Porte", "*série", "*ouvre", "*le", "*ciel.",
  "*Sève", "*pulse", "*comme", "*une", "*horloge.",
  "*Écureuil", "*hacker", "*vole", "*des", "*graines.",
  "*Étoiles", "*faibles", "*pilotent", "*le", "*voilier.",
  "*Lacs", "*en", "*RAID", "*miroirs", "*dupliqués.",
  "*Montagne", "*aircooling", "*apaise", "*les", "*circuits.",
  "*Verger", "*low-tech", "*compile", "*du", "*cidre.",
  "*Chouette", "*nocturne", "*ping", "*la", "*vallée.",
  "*Cigales", "*clock", "*vibrent", "*au", "*crépuscule.",
  "*Racines", "*maillées", "*réparent", "*la", "*panne.",
  "*Plumes", "*en", "*ASCII", "*tracent", "*le", "*vent.",
  "*Ruche", "*ouverte", "*partage", "*les", "*trames.",
  "*Brouillard", "*diffuse", "*la", "*bande", "*passante.",
  "*Aube", "*sobre", "*efface", "*les", "*logs."
};
